### PR TITLE
fix: PR #40 other bug.

### PR DESCRIPTION
**Pull request by SeanCraven314**
Hi Again,

As mentioned in the #40, there is another problem when tensor ndim == 1 I'm not sure entirely what this is doing, but again I got the inference to work. It would be good if this could be reviewed.

### CODE REVIEW

**Comment by Efficient-Large-Language-Model** [comment]
Sorry I just rolled back your previous PR because it breaks other cases. Potentially it is fixed here. Could you rebase and we will review.

**Comment by Efficient-Large-Language-Model** [comment]
See my reply in https://github.com/Efficient-Large-Model/VILA/issues/39
Looks like this is not needed?

**Comment by SeanCraven314** [comment]
> See my reply in #39 Looks like this is not needed?

I agree we should close. I'm sorry for the breaking change.

**Comment by nan2088** [comment]
i think tis PR may need reopen as #39 not really resoved

**Pull request closed without merging**
